SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
FPS = 60
BACKGROUND_COLOR = (135, 205, 235) # Light blue

#SETINGS GAME
GAME_SPEED = 5

#SETINGS CHO CHUONG NGAI VAT
PIPE_WIDTH = 50
PIPE_GAP = 150
PIPE_FREQUENCY = 1500  # milliseconds

#SETINGS WEBCAM
#CHANGE THE INDEX IF NEEDED
#NEU WEBCAM USB HOAC IVCAM, THI THUONG LA 0 HOAC 1
#NEU LA LUONG IP TU IVCAM, HAY DIEN URL (VD: "http://192.1.543:8080/video")
CAMERA_SOURCE = 0
